### ISSUE TITLE
спорные классы по БЭМ

### ISSUE THREAD

**Issue by cjbars** [blueberryfox/web-project#2]
классы описывающие модификатор, не должны описывать саму модификацию, они должны описывать изменение состояния элемента
например вместо
```
.menu-main__item_highlited-item
```
правильнее сделать
```
.menu-main__item_active
```
а эти стили, можно вынести в общие стили для текста
```
/*вместо*/
.about__content_bold
.about__content_italic
/* сделать */
.text-bold
.text-italic
```
хотя для последних двух стилей есть простые теги ```<strong> и <i>```

**Comment by cjbars** [comment]
menu-main__item_passiv

у пункта есть обычное стостояние
а так же модифицированные
- active
- disabled
- focused
- superPuperState

поэтому это:
```
<li class="menu-main__item menu-main__item_activ">Start</li>
<li class="menu-main__item"><a class="menu-main__item_passiv href=" href="about.html">About</a></li>
```
должно выглядеть примерно так:
```
<li class="menu-main__item menu-main__item_active">Start</li>
<li class="menu-main__item"><a href="about.html">About</a></li>
```
если вы хотите стилизовать ссылку в меню то тогда надо сделать так

```
<li class="menu-main__item menu-main__item_active">Start</li>
<li class="menu-main__item"><a class="menu-main__item_link" href="about.html">About</a></li>
```
если не очень понятно стучите в телеграмм

**Comment by bluberryfox** [comment]
https://github.com/blueberryfox/web-project/commit/1517f95d6048f1b2dd5a3fcba2b21f988dbd6f42

**Comment by cjbars** [comment]
ок
