### ISSUE TITLE
на линуксе не заработает

### ISSUE THREAD

**Issue by cjbars** [blueberryfox/web-project#3]
```php
public static function getPage($page_number) {
        return (include ('assets/' . Manager::$pages[$page_number]).'.html');
    }
```
Этот метод подключает файлик.  
Название файлика берется из массива. В массиве:
```php
public static $pages = array(
        0 => 'Start',
        1 => 'About',
        2 => 'Toplist'
    );
```
значит он будет искать ```assets/Start.html```
а в директории ```assets/start.html```

для линукс систем это два разных названия.

поправьте пожалуйста.

**Comment by bluberryfox** [comment]
https://github.com/blueberryfox/web-project/commit/221c39dcf33658626a7c6ea6e3a3f93f7754f4be
